bind = "0.0.0.0:8001"
grpc_bind = "0.0.0.0:7001"
domain = "localhost"

resources_endpoint = "https://api.sn.solsynth.dev/cgi/uc"

templates_dir = "./templates"
ip_block_path = "./ip_block.list"

rate_limit = 120
rate_limit_advance = 60

[debug]
database = false
print_routes = false

[database]
dsn = "host=localhost user=postgres dbname=postgres password=password port=5432 sslmode=disable"
prefix = "sn_"

[mq]
addr = "nats.orb.local:4222"

[kv]
endpoints = ["etcd.orb.local:2379"]

[cache]
addr = "redis.orb.local:6379"
password = ""

[security]
public_key = "keys/public_key.pem"
internal_public_key = "keys/internal_public_key.pem"
internal_private_key = "keys/internal_private_key.pem"

[watchtower]
database_backups = "./backups"

[captcha]
provider = "turnstile"
api_key = ""
api_secret = ""
