bind = "0.0.0.0:8001"
grpc_bind = "0.0.0.0:7001"
domain = "localhost"

rate_limit = 120

[debug]
database = false
print_routes = false

[database]
dsn = "host=localhost user=postgres dbname=postgres password=password port=5432 sslmode=disable"
prefix = "sn_"

[mq]
addr = "localhost:4222"

[kv]
endpoints = ["localhost:2379"]

[security]
public_key = "keys/public_key.pem"
internal_public_key = "keys/internal_public_key.pem"
internal_private_key = "keys/internal_private_key.pem"

[watchtower]
database_backups = "./backups"
