// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *CommandInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CommandInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CommandLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandLookupRequest) Reset() {
	*x = CommandLookupRequest{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLookupRequest) ProtoMessage() {}

func (x *CommandLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLookupRequest.ProtoReflect.Descriptor instead.
func (*CommandLookupRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandLookupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommandLookupRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type AddCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommandResponse) Reset() {
	*x = AddCommandResponse{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommandResponse) ProtoMessage() {}

func (x *AddCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommandResponse.ProtoReflect.Descriptor instead.
func (*AddCommandResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *AddCommandResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type RemoveCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCommandResponse) Reset() {
	*x = RemoveCommandResponse{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCommandResponse) ProtoMessage() {}

func (x *RemoveCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCommandResponse.ProtoReflect.Descriptor instead.
func (*RemoveCommandResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveCommandResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type CommandArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandArgument) Reset() {
	*x = CommandArgument{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandArgument) ProtoMessage() {}

func (x *CommandArgument) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandArgument.ProtoReflect.Descriptor instead.
func (*CommandArgument) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

func (x *CommandArgument) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandArgument) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CommandArgument) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CommandReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDelivered   bool                   `protobuf:"varint,1,opt,name=is_delivered,json=isDelivered,proto3" json:"is_delivered,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReturn) Reset() {
	*x = CommandReturn{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReturn) ProtoMessage() {}

func (x *CommandReturn) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReturn.ProtoReflect.Descriptor instead.
func (*CommandReturn) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *CommandReturn) GetIsDelivered() bool {
	if x != nil {
		return x.IsDelivered
	}
	return false
}

func (x *CommandReturn) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommandReturn) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CommandReturn) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\x05proto\"I\n" +
	"\vCommandInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\">\n" +
	"\x14CommandLookupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"3\n" +
	"\x12AddCommandResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\"6\n" +
	"\x15RemoveCommandResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\"n\n" +
	"\x0fCommandArgument\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1d\n" +
	"\apayload\x18\x03 \x01(\fH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload\"\x98\x01\n" +
	"\rCommandReturn\x12!\n" +
	"\fis_delivered\x18\x01 \x01(\bR\visDelivered\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\apayload\x18\x04 \x01(\fH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload2\xa6\x02\n" +
	"\x0fCommandProvider\x12=\n" +
	"\n" +
	"AddCommand\x12\x12.proto.CommandInfo\x1a\x19.proto.AddCommandResponse\"\x00\x12L\n" +
	"\rRemoveCommand\x12\x1b.proto.CommandLookupRequest\x1a\x1c.proto.RemoveCommandResponse\"\x00\x12=\n" +
	"\vSendCommand\x12\x16.proto.CommandArgument\x1a\x14.proto.CommandReturn\"\x00\x12G\n" +
	"\x11SendStreamCommand\x12\x16.proto.CommandArgument\x1a\x14.proto.CommandReturn\"\x00(\x010\x01B\tZ\a.;protob\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_command_proto_goTypes = []any{
	(*CommandInfo)(nil),           // 0: proto.CommandInfo
	(*CommandLookupRequest)(nil),  // 1: proto.CommandLookupRequest
	(*AddCommandResponse)(nil),    // 2: proto.AddCommandResponse
	(*RemoveCommandResponse)(nil), // 3: proto.RemoveCommandResponse
	(*CommandArgument)(nil),       // 4: proto.CommandArgument
	(*CommandReturn)(nil),         // 5: proto.CommandReturn
}
var file_command_proto_depIdxs = []int32{
	0, // 0: proto.CommandProvider.AddCommand:input_type -> proto.CommandInfo
	1, // 1: proto.CommandProvider.RemoveCommand:input_type -> proto.CommandLookupRequest
	4, // 2: proto.CommandProvider.SendCommand:input_type -> proto.CommandArgument
	4, // 3: proto.CommandProvider.SendStreamCommand:input_type -> proto.CommandArgument
	2, // 4: proto.CommandProvider.AddCommand:output_type -> proto.AddCommandResponse
	3, // 5: proto.CommandProvider.RemoveCommand:output_type -> proto.RemoveCommandResponse
	5, // 6: proto.CommandProvider.SendCommand:output_type -> proto.CommandReturn
	5, // 7: proto.CommandProvider.SendStreamCommand:output_type -> proto.CommandReturn
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_command_proto_msgTypes[4].OneofWrappers = []any{}
	file_command_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
