// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: database.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseController_AllocDatabase_FullMethodName = "/proto.DatabaseController/AllocDatabase"
)

// DatabaseControllerClient is the client API for DatabaseController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabaseControllerClient interface {
	AllocDatabase(ctx context.Context, in *AllocDatabaseRequest, opts ...grpc.CallOption) (*AllocDatabaseResponse, error)
}

type databaseControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseControllerClient(cc grpc.ClientConnInterface) DatabaseControllerClient {
	return &databaseControllerClient{cc}
}

func (c *databaseControllerClient) AllocDatabase(ctx context.Context, in *AllocDatabaseRequest, opts ...grpc.CallOption) (*AllocDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseController_AllocDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseControllerServer is the server API for DatabaseController service.
// All implementations must embed UnimplementedDatabaseControllerServer
// for forward compatibility.
type DatabaseControllerServer interface {
	AllocDatabase(context.Context, *AllocDatabaseRequest) (*AllocDatabaseResponse, error)
	mustEmbedUnimplementedDatabaseControllerServer()
}

// UnimplementedDatabaseControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseControllerServer struct{}

func (UnimplementedDatabaseControllerServer) AllocDatabase(context.Context, *AllocDatabaseRequest) (*AllocDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocDatabase not implemented")
}
func (UnimplementedDatabaseControllerServer) mustEmbedUnimplementedDatabaseControllerServer() {}
func (UnimplementedDatabaseControllerServer) testEmbeddedByValue()                            {}

// UnsafeDatabaseControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseControllerServer will
// result in compilation errors.
type UnsafeDatabaseControllerServer interface {
	mustEmbedUnimplementedDatabaseControllerServer()
}

func RegisterDatabaseControllerServer(s grpc.ServiceRegistrar, srv DatabaseControllerServer) {
	// If the following call pancis, it indicates UnimplementedDatabaseControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseController_ServiceDesc, srv)
}

func _DatabaseController_AllocDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseControllerServer).AllocDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseController_AllocDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseControllerServer).AllocDatabase(ctx, req.(*AllocDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseController_ServiceDesc is the grpc.ServiceDesc for DatabaseController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DatabaseController",
	HandlerType: (*DatabaseControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocDatabase",
			Handler:    _DatabaseController_AllocDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database.proto",
}
